### ISSUE TITLE
Config loading

### ISSUE THREAD

**Issue by cherez** [siggame/server#10]
Build in config file loading for games.

**Comment by russleyshaw** [comment]
What would the config do that the codegen wouldn't?

**Comment by cherez** [comment]
The server config is to make it easy to change game constants to tweak game settings.

The codegen config defines the protocol.

**Comment by russleyshaw** [comment]
Oh duh. Please make it less confusing than the previous framework. It was difficult to tell when and where they were read.

**Comment by cherez** [comment]
Well, the old framework didn't actually have config stuff built in; it was an innovation invented well later.

This time I'm hoping that there will just be a config variable with all the data loaded when the game begins.
