### ISSUE TITLE
Logging

### ISSUE THREAD

**Issue by cherez** [siggame/server#13]
We should log events in games, save them, and send them back to the clients on request for the visualizer(s).

**Comment by cherez** [comment]
Questions:

How do we want to store the logs?
Uncompressed is an option, but gzip and bz2 should save a lot of space. Any word on how well the visualizers could cope with these?

Would client-side logging be easier? 
This would simplify things on the server, but complicate the clients. It would save bandwidth duplicated by effectively sending the log twice. It would have problems in games with stealth mechanics where the logs couldn't record what was hidden during the game.

**Comment by russleyshaw** [comment]
- Logs
  I think they should be compressed. They will need to be sent over the network anyways if downloaded from the site and viewed on the visualizer. I have no problem with any compression type, so gzip and bz2 sound fine.
- Client-side logging
  I am fine with writing logging into the client, but I believe competitors should see all of the game once a winner is decided and I am not sure how we would send and record hidden objects (stealthed) over the network safely.
