### ISSUE TITLE
Decide on encoding

### ISSUE THREAD

**Issue by cherez** [siggame/server#3]
The old framework is ASCII-encoded, but I'd like to do UTF 8 if we can. Unicode is fun and if anyone besides some guys in the middle of the US use it, unicode would make it much nicer.

I'd say the real question is whether it would make any components any harder:
- Server don't care
- Clients
  - Python client don't care
  - C++ client would see this as a byte array, so if you're fiddling with it it might look bad?
  - Java client ??? Java is supposed to be unicode-compliant, but they seemed to think a char is 16 bits?
  - This probably won't be too big a deal since things with strings are more visualizer focused than client focused
- Visualizers
  - ????

**Comment by jacobgardner** [comment]
@JacobFischer needs to answer this.  The python visualizer can handle utf fine.  I'd assume the web-visualizer can, though since so much of the web is utf-8.

**Comment by cherez** [comment]
UTF-8 it is!
