### ISSUE TITLE
Fill in game logic

### ISSUE THREAD

**Issue by cherez** [siggame/server#7]
The Game is pretty stubby right now. We want it to be everything that isn't game-specific, and to call child class methods for the game-specific stuff.
- [x] Implement "flushing"
- [x] Game initialization
- [x] Turn changing
- [x] Winner determination
- [x] Game ending

Feel free to add more or make sub-issues for anything here

**Comment by russleyshaw** [comment]
I think the "next turn" message should contain an argument containing the player ID of who's turn it is next. This would be very useful for any future game that might have a "skip turn" or more than two players.

**Comment by cherez** [comment]
The reason it presently doesn't is the current turn's player ID is already in the game globals, so the clients already "know". If you think providing the information on the turn-change messages as well makes the clients easier, it's just a small code addition to the server and a small increase in communication size.

**Comment by russleyshaw** [comment]
As long as it is possible for a client to figure out if it is its turn or not, that is fine.
